import { jsonError } from '@/lib/serverAuth'
import { requireSuperAdmin } from '@/lib/staffAuth'
import { isStaffRole,STAFF_ROLES } from '@/lib/staffRoles'
import { rateLimit } from '@/lib/rateLimit'

const date=(value:any)=>value?.toDate?.()?.toISOString?.()||null
export async function GET(request:Request){try{const{admin}=await requireSuperAdmin(request);const[staff,audit]=await Promise.all([admin.db.collection('users').where('operationalRole','in',[...STAFF_ROLES]).limit(100).get(),admin.db.collection('staffRoleAudit').orderBy('createdAt','desc').limit(50).get()]);return Response.json({ok:true,staff:staff.docs.map(document=>({id:document.id,email:document.data().email,displayName:document.data().displayName,operationalRole:document.data().operationalRole,staffStatus:document.data().staffStatus,staffAssignedAt:date(document.data().staffAssignedAt)})),audit:audit.docs.map(document=>({id:document.id,...document.data(),createdAt:date(document.data().createdAt)})),roles:STAFF_ROLES})}catch(error){return jsonError(error)}}

export async function POST(request:Request){try{rateLimit(request,'staff-assignment',10);const{user,admin}=await requireSuperAdmin(request),input=await request.json(),email=String(input.email||'').trim().toLowerCase(),role=input.role===null?null:String(input.role||'');if(!email||role!==null&&!isStaffRole(role))return Response.json({ok:false,error:'Enter a valid email and operational role.'},{status:400});const target=await admin.auth.getUserByEmail(email);if(!target.emailVerified)return Response.json({ok:false,error:'This account must verify its email before receiving staff access.'},{status:409});if(target.uid===user.id&&role!=='super_admin')return Response.json({ok:false,error:'The system owner cannot remove their own super administrator authority.'},{status:409});const profile=admin.db.collection('users').doc(target.uid),snapshot=await profile.get(),previousRole=snapshot.data()?.operationalRole||null,claims={...(target.customClaims||{})};if(role)claims.operationalRole=role;else delete claims.operationalRole;await admin.auth.setCustomUserClaims(target.uid,claims);await admin.db.runTransaction(async transaction=>{transaction.set(profile,{email,displayName:target.displayName||snapshot.data()?.displayName||email.split('@')[0],operationalRole:role,staffStatus:role?'active':'revoked',staffAssignedBy:user.id,staffAssignedAt:new Date(),updatedAt:new Date()},{merge:true});transaction.set(admin.db.collection('staffRoleAudit').doc(),{targetUid:target.uid,targetEmail:email,previousRole,newRole:role,assignedBy:user.id,assignedByEmail:user.email,createdAt:new Date()})});await admin.auth.revokeRefreshTokens(target.uid);return Response.json({ok:true,email,role,message:role?'Role assigned. Existing sessions were revoked.':'Staff access revoked. Existing sessions were revoked.'})}catch(error:any){if(error?.code==='auth/user-not-found')return Response.json({ok:false,error:'No Firebase account exists for that email.'},{status:404});return jsonError(error)}}
