'use client'
import { useEffect,useState } from 'react'
import { motion } from 'framer-motion'
import { authenticatedFetch } from '@/lib/apiClient'
const MotionDiv=motion.div as any

const descriptions:Record<string,string>={support_agent:'Communicates on cases and gathers evidence.',dispute_officer:'Makes dispute decisions.',finance_operator:'Approves and records payouts and refunds.',risk_officer:'Investigates exception flags and high-risk cases.',admin:'Oversees operations queues.',super_admin:'Assigns staff roles and controls critical configuration.'}
export default function AdminOperations(){const[data,setData]=useState<any>(null),[email,setEmail]=useState(''),[role,setRole]=useState('support_agent'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{try{setData(await authenticatedFetch('/api/admin/staff'));setMessage('')}catch(error:any){setMessage(error.message)}}
 useEffect(()=>{void load()},[])
 const assign=async(revoke=false,targetEmail=email)=>{setBusy(true);setMessage('');try{const result=await authenticatedFetch('/api/admin/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:targetEmail,role:revoke?null:role})});setMessage(result.message);setEmail('');await load()}catch(error:any){setMessage(error.message)}finally{setBusy(false)}}
 return <MotionDiv initial={{opacity:0}} animate={{opacity:1}} className="mx-auto max-w-7xl space-y-8 py-8">
  <div className="rounded-[2rem] bg-gradient-to-br from-[var(--afrigo-primary-green)] to-emerald-800 p-6 text-white shadow-2xl sm:p-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-300">Restricted control plane</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Operations administration</h1><p className="mt-3 max-w-3xl text-sm text-white/80 sm:text-base">Assign one operational responsibility per verified company account. Every change is attributed, audited, and immediately revokes the staff member’s existing sessions.</p></div>
  <section className="grid gap-6 rounded-[2rem] border bg-white p-5 shadow-xl lg:grid-cols-[1fr_1.3fr] sm:p-8"><form onSubmit={event=>{event.preventDefault();void assign()}} className="space-y-4"><div><label className="text-sm font-bold">Verified staff email</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com" className="mt-2 w-full rounded-2xl border px-4 py-3"/></div><div><label className="text-sm font-bold">Operational role</label><select value={role} onChange={e=>setRole(e.target.value)} className="mt-2 w-full rounded-2xl border px-4 py-3">{(data?.roles||Object.keys(descriptions)).map((item:string)=><option key={item} value={item}>{item.replaceAll('_',' ')}</option>)}</select><p className="mt-2 text-sm text-[var(--afrigo-text-secondary)]">{descriptions[role]}</p></div><button disabled={busy} className="w-full rounded-2xl bg-[var(--afrigo-primary-green)] px-5 py-3 font-bold text-white transition hover:-translate-y-0.5 disabled:opacity-50">{busy?'Applying access…':'Assign role and revoke sessions'}</button>{message&&<p role="status" className="rounded-xl bg-[var(--afrigo-bg)] p-3 text-sm">{message}</p>}</form>
   <div><h2 className="text-xl font-black text-[var(--afrigo-primary-green)]">Active operational staff</h2><div className="mt-4 space-y-3">{(data?.staff||[]).map((member:any)=><MotionDiv layout key={member.id} className="flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{member.displayName||member.email}</p><p className="text-sm text-[var(--afrigo-text-secondary)]">{member.email} · {String(member.operationalRole).replaceAll('_',' ')}</p></div><button disabled={busy} onClick={()=>void assign(true,member.email)} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Revoke</button></MotionDiv>)}{data&&!data.staff?.length&&<p className="rounded-2xl bg-[var(--afrigo-bg)] p-5 text-sm">No staff roles assigned yet.</p>}</div></div>
  </section>
  <section className="rounded-[2rem] border bg-white p-5 shadow-xl sm:p-8"><h2 className="text-xl font-black text-[var(--afrigo-primary-green)]">Assignment audit trail</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Staff account</th><th className="p-3">Previous</th><th className="p-3">New role</th><th className="p-3">Assigned by</th><th className="p-3">Time</th></tr></thead><tbody>{(data?.audit||[]).map((item:any)=><tr key={item.id} className="border-b last:border-0"><td className="p-3">{item.targetEmail}</td><td className="p-3">{item.previousRole||'none'}</td><td className="p-3 font-bold">{item.newRole||'revoked'}</td><td className="p-3">{item.assignedByEmail}</td><td className="p-3">{item.createdAt?new Date(item.createdAt).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section>
 </MotionDiv>}
