create extension if not exists pgcrypto;

create table if not exists public.companies (id uuid primary key default gen_random_uuid(), name text not null, country text, kyc_status text not null default 'pending' check (kyc_status in ('pending','verified','rejected')), owner_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.users (id uuid primary key references auth.users(id) on delete cascade, email text unique, display_name text, role text check (role in ('Buyer','Seller','Exporter')), company_id uuid references public.companies(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.lots (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, company_id uuid references public.companies(id), title text not null, description text, quantity numeric not null check(quantity >= 0), unit text not null default 'kg', grade text, price numeric check(price >= 0), origin text, photos jsonb not null default '[]', status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.rfqs (id uuid primary key default gen_random_uuid(), buyer_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, quantity numeric not null check(quantity > 0), unit text not null default 'kg', destination_country text not null, budget text, deadline date, status text not null default 'Open', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bids (id uuid primary key default gen_random_uuid(), rfq_id uuid not null references public.rfqs(id) on delete cascade, supplier_id uuid not null references auth.users(id) on delete cascade, price numeric not null check(price > 0), delivery text, terms jsonb not null default '{}', status text not null default 'Submitted', created_at timestamptz not null default now(), unique(rfq_id,supplier_id));
create table if not exists public.contracts (id uuid primary key default gen_random_uuid(), rfq_id uuid references public.rfqs(id), buyer_id uuid not null references auth.users(id), supplier_id uuid not null references auth.users(id), amount numeric not null check(amount >= 0), status text not null default 'pending', metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.shipments (id uuid primary key default gen_random_uuid(), contract_id uuid references public.contracts(id), exporter_id uuid references auth.users(id), status text not null default 'Scheduled', carrier text, eta date, location text, tracking jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.warehouses (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null, location jsonb not null default '{}', capacity numeric, created_at timestamptz not null default now());
create table if not exists public.pickups (id uuid primary key default gen_random_uuid(), exporter_id uuid not null references auth.users(id), warehouse_location text not null, container_count integer not null check(container_count > 0), estimated_weight text, preferred_date date not null, carrier text, status text not null default 'Scheduled', created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.contracts(id), payer_id uuid not null references auth.users(id), provider text, provider_reference text unique, amount numeric not null check(amount > 0), currency text not null default 'USD', status text not null default 'pending', released boolean not null default false, tx_meta jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.documents (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, shipment_id uuid references public.shipments(id), type text not null, status text not null default 'Submitted', meta jsonb not null default '{}', storage_path text not null, created_at timestamptz not null default now());
create table if not exists public.compliance_actions (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), shipment_id uuid references public.shipments(id), category text not null, requirement text not null, status text not null default 'Pending', due_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.activity_logs (id uuid primary key default gen_random_uuid(), actor_id uuid not null references auth.users(id) on delete cascade, type text not null, label text not null, detail text, role text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.integration_events (id uuid primary key default gen_random_uuid(), provider text not null, external_id text not null, event_type text not null, payload jsonb not null default '{}', processed_at timestamptz, created_at timestamptz not null default now(), unique(provider,external_id));

alter table public.companies enable row level security; alter table public.users enable row level security; alter table public.lots enable row level security; alter table public.rfqs enable row level security; alter table public.bids enable row level security; alter table public.contracts enable row level security; alter table public.shipments enable row level security; alter table public.warehouses enable row level security; alter table public.pickups enable row level security; alter table public.payments enable row level security; alter table public.documents enable row level security; alter table public.compliance_actions enable row level security; alter table public.activity_logs enable row level security; alter table public.integration_events enable row level security;

create policy "own profile" on public.users for all using (id=auth.uid()) with check (id=auth.uid());
create policy "own companies" on public.companies for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "lots readable" on public.lots for select to authenticated using (true); create policy "manage own lots" on public.lots for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "rfqs readable" on public.rfqs for select to authenticated using(true); create policy "manage own rfqs" on public.rfqs for all using(buyer_id=auth.uid()) with check(buyer_id=auth.uid());
create policy "bids visible to parties" on public.bids for select using(supplier_id=auth.uid() or exists(select 1 from public.rfqs r where r.id=rfq_id and r.buyer_id=auth.uid())); create policy "supplier manages bids" on public.bids for all using(supplier_id=auth.uid()) with check(supplier_id=auth.uid());
create policy "contracts parties" on public.contracts for select using(buyer_id=auth.uid() or supplier_id=auth.uid());
create policy "shipments parties" on public.shipments for select using(exporter_id=auth.uid() or exists(select 1 from public.contracts c where c.id=contract_id and (c.buyer_id=auth.uid() or c.supplier_id=auth.uid()))); create policy "exporter shipments" on public.shipments for all using(exporter_id=auth.uid()) with check(exporter_id=auth.uid());
create policy "own warehouses" on public.warehouses for all using(owner_id=auth.uid()) with check(owner_id=auth.uid()); create policy "own pickups" on public.pickups for all using(exporter_id=auth.uid()) with check(exporter_id=auth.uid());
create policy "payment parties" on public.payments for select using(payer_id=auth.uid() or exists(select 1 from public.contracts c where c.id=contract_id and (c.buyer_id=auth.uid() or c.supplier_id=auth.uid())));
create policy "own documents" on public.documents for all using(owner_id=auth.uid()) with check(owner_id=auth.uid()); create policy "own compliance" on public.compliance_actions for all using(owner_id=auth.uid()) with check(owner_id=auth.uid()); create policy "own activities" on public.activity_logs for all using(actor_id=auth.uid()) with check(actor_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('kyc','kyc',false,20971520,array['application/pdf','image/jpeg','image/png']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "kyc owner upload" on storage.objects for insert to authenticated with check(bucket_id='kyc' and (storage.foldername(name))[1]=auth.uid()::text); create policy "kyc owner read" on storage.objects for select to authenticated using(bucket_id='kyc' and (storage.foldername(name))[1]=auth.uid()::text); create policy "kyc owner delete" on storage.objects for delete to authenticated using(bucket_id='kyc' and (storage.foldername(name))[1]=auth.uid()::text);
