'use client'
import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { authenticatedFetch } from '@/lib/apiClient'
import type { Role } from '@/lib/roles'
const MotionSection = motion.section as any

export default function TradeOperations({ role }: { role: Role }) {
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0)
  const load=async()=>{try{setError('');setData(await authenticatedFetch('/api/dashboard'))}catch(e:any){setError(e.message)}}
  useEffect(()=>{void load()},[role])
  const rfqs=useMemo(()=>((data?.rfqs||[]) as any[]).filter(item=>String(item.title||'').toLowerCase().includes(search.toLowerCase())).slice(page*10,page*10+10),[data,search,page])
  const act=async(action:string,contractId:string)=>{const value=['cancel','dispute','refund'].includes(action)?prompt(`Reason for ${action}`)||'':action==='milestone'?prompt('New fulfilment milestone')||'':action==='message'?prompt('Message')||'':'';setBusy(contractId+action);try{await authenticatedFetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,contractId,reason:value,milestone:value,message:value})});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  const pay=async(contractId:string)=>{setBusy(contractId+'pay');try{const result=await authenticatedFetch('/api/payments/initialize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractId})});location.assign(result.authorizationUrl)}catch(e:any){setError(e.message)}finally{setBusy('')}}
  const assign=async(contractId:string)=>{const exporterId=prompt('Enter the verified Exporter user ID');if(!exporterId)return;setBusy(contractId+'assign');try{await authenticatedFetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign-exporter',contractId,exporterId})});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  if(error&&!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>
  return <MotionSection initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="rounded-3xl border border-[var(--afrigo-border)] bg-white p-5 shadow-xl sm:p-8">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--afrigo-secondary-gold)]">Live operations</p><h2 className="mt-2 text-2xl font-black text-[var(--afrigo-primary-green)]">{role} workspace records</h2></div>{(role==='Buyer'||role==='Seller')&&<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Search RFQs" className="rounded-xl border border-[var(--afrigo-border)] px-4 py-2"/>}</div>
    {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {(role==='Buyer'||role==='Seller')&&<div className="mt-6"><h3 className="font-bold">RFQs</h3><div className="mt-3 grid gap-3">{rfqs.map(item=><div key={item.id} className="rounded-xl bg-[var(--afrigo-bg)] p-4"><div className="flex justify-between gap-3"><span className="font-semibold">{item.title}</span><span className="text-sm">{item.status}</span></div><p className="text-sm text-[var(--afrigo-text-secondary)]">{item.quantity} {item.unit} · {item.destination_country}</p></div>)}{!rfqs.length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No matching RFQs.</p>}</div><div className="mt-3 flex gap-2"><button disabled={!page} onClick={()=>setPage(v=>v-1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Previous</button><button disabled={(data?.rfqs||[]).length<=(page+1)*10} onClick={()=>setPage(v=>v+1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Next</button></div></div>}
    <div className="mt-7"><h3 className="font-bold">Contracts and payments</h3><div className="mt-3 grid gap-3">{(data?.contracts||[]).map((item:any)=><div key={item.id} className="rounded-2xl border border-[var(--afrigo-border)] p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold">Contract {item.id.slice(0,8)}</span><span className="rounded-full bg-[var(--afrigo-primary-green-light)] px-3 py-1 text-xs font-bold text-white">{item.status}</span></div><p className="mt-2 text-sm">{item.currency} {Number(item.amount||0).toLocaleString()} · Payment: {item.paymentStatus||'not started'} · Payout: {item.payoutStatus||'pending'}</p><div className="mt-3 flex flex-wrap gap-2">{role==='Buyer'&&item.status==='accepted'&&<button onClick={()=>pay(item.id)} className="rounded-lg bg-[var(--afrigo-primary-green)] px-3 py-2 text-sm text-white">Pay securely</button>}{role==='Buyer'&&item.status==='paid'&&<button onClick={()=>assign(item.id)} className="rounded-lg bg-[var(--afrigo-primary-green)] px-3 py-2 text-sm text-white">Assign Exporter</button>}{role==='Seller'&&item.status==='pending'&&<button onClick={()=>act('accept',item.id)} className="rounded-lg bg-[var(--afrigo-primary-green)] px-3 py-2 text-sm text-white">Accept contract</button>}{role==='Seller'&&['accepted','paid','fulfilling'].includes(item.status)&&<button onClick={()=>act('milestone',item.id)} className="rounded-lg border px-3 py-2 text-sm">Update milestone</button>}<button onClick={()=>act('message',item.id)} className="rounded-lg border px-3 py-2 text-sm">Message</button>{['pending','accepted'].includes(item.status)&&<button onClick={()=>act('cancel',item.id)} className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700">Cancel</button>}<button onClick={()=>act('dispute',item.id)} className="rounded-lg border px-3 py-2 text-sm">Dispute</button>{role==='Buyer'&&['paid','disputed'].includes(item.status)&&<button onClick={()=>act('refund',item.id)} className="rounded-lg border px-3 py-2 text-sm">Request refund</button>}</div></div>)}{!(data?.contracts||[]).length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No contracts yet.</p>}</div></div>
  </MotionSection>
}
