'use client'
import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { authenticatedFetch } from '@/lib/apiClient'
import type { Role } from '@/lib/roles'
const MotionSection = motion.section as any
const button='rounded-xl border border-[var(--afrigo-border)] px-3 py-2 text-sm font-semibold transition hover:-translate-y-0.5 hover:border-[var(--afrigo-primary-green)] disabled:opacity-40'

export default function TradeOperations({role}:{role:Role}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[exporter,setExporter]=useState<Record<string,string>>({}),[tracking,setTracking]=useState<Record<string,string>>({})
 const load=async()=>{try{setError('');setData(await authenticatedFetch('/api/dashboard'))}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[role])
 const filtered=useMemo(()=>((data?.rfqs||[]) as any[]).filter(item=>String(item.title||'').toLowerCase().includes(search.toLowerCase())),[data,search]),rfqs=filtered.slice(page*10,page*10+10)
 const request=async(key:string,url:string,body?:any)=>{setBusy(key);try{const result=await authenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();return result}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const act=async(action:string,contractId:string)=>{const needs=['cancel','dispute','refund','milestone','message'].includes(action),value=needs?prompt(action==='milestone'?'New fulfilment milestone':action==='message'?'Message':`Reason for ${action}`)||'':'';if(needs&&!value)return;await request(contractId+action,'/api/operations',{action,contractId,reason:value,milestone:value,message:value})}
 const pay=async(id:string)=>{setBusy(id+'pay');try{const result=await authenticatedFetch('/api/payments/initialize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractId:id})});location.assign(result.authorizationUrl)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const settle=async()=>{const accountNumber=prompt('Settlement account number'),bankCode=accountNumber&&prompt('Paystack bank code');if(accountNumber&&bankCode)await request('settlement','/api/settlement',{accountNumber,bankCode})}
 const track=async(id:string)=>{setBusy(id+'track');try{const result=await authenticatedFetch(`/api/logistics/track?shipmentId=${encodeURIComponent(id)}`),shipment=result.data?.shipments?.[0],event=shipment?.events?.[0];setTracking(v=>({...v,[id]:event?.description||shipment?.status?.statusCode||'Tracking received'}))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const milestone=async(id:string)=>{const status=prompt('Milestone: Picked Up, In Transit, Customs Clearance, Cleared, or Delivered'),trackingNumber=prompt('Carrier tracking number (optional)')||'';if(status)await request(id+'ship','/api/shipments/milestone',{shipmentId:id,status,trackingNumber,carrier:'DHL'})}
 if(error&&!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>
 return <MotionSection initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="rounded-3xl border border-[var(--afrigo-border)] bg-white p-5 shadow-xl sm:p-8">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--afrigo-secondary-gold)]">Live operations</p><h2 className="mt-2 text-2xl font-black text-[var(--afrigo-primary-green)]">{role} workspace records</h2></div><div className="flex gap-2">{role==='Seller'&&<button onClick={settle} className={button}>Set payout account</button>}{(role==='Buyer'||role==='Seller')&&<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Search RFQs" className="min-w-0 rounded-xl border px-4 py-2"/>}</div></div>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {role==='Seller'&&data?.metrics&&<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Bids',data.metrics.totalBids],['Win rate',`${data.metrics.winRate}%`],['Completed',data.metrics.completedContracts],['Verified revenue',Number(data.metrics.revenue).toLocaleString()]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-[var(--afrigo-bg)] p-4"><p className="text-xs text-[var(--afrigo-text-secondary)]">{label}</p><p className="mt-1 text-xl font-black text-[var(--afrigo-primary-green)]">{value}</p></div>)}</div>}
  {(role==='Buyer'||role==='Seller')&&<div className="mt-6"><h3 className="font-bold">RFQs</h3><div className="mt-3 grid gap-3">{rfqs.map(item=><div key={item.id} className="rounded-xl bg-[var(--afrigo-bg)] p-4"><div className="flex justify-between gap-3"><span className="font-semibold">{item.title}</span><span className="text-sm">{item.status}</span></div><p className="text-sm text-[var(--afrigo-text-secondary)]">{item.quantity} {item.unit} · {item.destination_country}</p></div>)}{!rfqs.length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No matching RFQs.</p>}</div><div className="mt-3 flex gap-2"><button disabled={!page} onClick={()=>setPage(v=>v-1)} className={button}>Previous</button><button disabled={filtered.length<=(page+1)*10} onClick={()=>setPage(v=>v+1)} className={button}>Next</button></div></div>}
  <div className="mt-7"><h3 className="font-bold">Contracts and payments</h3><div className="mt-3 grid gap-3">{(data?.contracts||[]).map((item:any)=><div key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold">Contract {item.id.slice(0,8)}</span><span className="rounded-full bg-[var(--afrigo-primary-green-light)] px-3 py-1 text-xs font-bold text-white">{item.status}</span></div><p className="mt-2 text-sm">{item.currency} {Number(item.amount||0).toLocaleString()} · Payment: {item.paymentStatus||'not started'} · Payout: {item.payoutStatus||'pending'}</p><div className="mt-3 flex flex-wrap gap-2">{role==='Buyer'&&item.status==='accepted'&&<button disabled={!!busy} onClick={()=>pay(item.id)} className={button}>Pay securely</button>}{role==='Buyer'&&item.status==='paid'&&<><select value={exporter[item.id]||''} onChange={e=>setExporter(v=>({...v,[item.id]:e.target.value}))} className={button}><option value="">Choose verified Exporter</option>{(data.exporters||[]).map((x:any)=><option key={x.id} value={x.id}>{x.displayName}{x.country?` · ${x.country}`:''}</option>)}</select><button disabled={!exporter[item.id]||!!busy} onClick={()=>request(item.id+'assign','/api/operations',{action:'assign-exporter',contractId:item.id,exporterId:exporter[item.id]})} className={button}>Assign</button></>}{role==='Seller'&&item.status==='pending'&&<button onClick={()=>act('accept',item.id)} className={button}>Accept contract</button>}{role==='Seller'&&['accepted','paid','fulfilling'].includes(item.status)&&<button onClick={()=>act('milestone',item.id)} className={button}>Update milestone</button>}<button onClick={()=>act('message',item.id)} className={button}>Message</button>{['pending','accepted'].includes(item.status)&&<button onClick={()=>act('cancel',item.id)} className={button}>Cancel</button>}<button onClick={()=>act('dispute',item.id)} className={button}>Dispute</button>{role==='Buyer'&&['paid','disputed'].includes(item.status)&&<button onClick={()=>act('refund',item.id)} className={button}>Request refund</button>}</div></div>)}{!(data?.contracts||[]).length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No contracts yet.</p>}</div></div>
  {!!(data?.shipments||[]).length&&<div className="mt-7"><h3 className="font-bold">Shipments</h3><div className="mt-3 grid gap-3">{data.shipments.map((item:any)=><div key={item.id} className="rounded-2xl border p-4"><div className="flex justify-between"><span className="font-semibold">Shipment {item.id.slice(0,8)}</span><span>{item.status}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[var(--afrigo-primary-green)] transition-all" style={{width:`${item.progress||0}%`}}/></div><div className="mt-3 flex gap-2">{role==='Exporter'?<button onClick={()=>milestone(item.id)} className={button}>Update shipment</button>:<button onClick={()=>track(item.id)} className={button}>Track with DHL</button>}</div>{tracking[item.id]&&<p className="mt-2 text-sm">{tracking[item.id]}</p>}</div>)}</div></div>}
 </MotionSection>
}
