import { jsonError } from '@/lib/serverAuth'
import { requireStaff } from '@/lib/staffAuth'
import { hasCapability } from '@/lib/staffRoles'
import { rateLimit } from '@/lib/rateLimit'

const rows=(snapshot:any)=>snapshot.docs.map((document:any)=>({id:document.id,...document.data()}))
export async function GET(request:Request){try{const{admin,staffRole}=await requireStaff(request),db=admin.db,result:any={ok:true,staffRole};if(hasCapability(staffRole,'cases:read')){const[cases,disputes]=await Promise.all([db.collection('supportCases').where('status','==','open').limit(50).get(),db.collection('contracts').where('status','==','disputed').limit(50).get()]);result.cases=rows(cases);result.disputes=rows(disputes)}if(hasCapability(staffRole,'finance:read')){const[refunds,payouts]=await Promise.all([db.collection('contracts').where('refundStatus','==','requested').limit(50).get(),db.collection('contracts').where('payoutStatus','==','pending').limit(50).get()]);result.refunds=rows(refunds);result.payouts=rows(payouts).filter((item:any)=>item.status==='completed'&&item.paymentStatus==='paid')}if(hasCapability(staffRole,'risk:read')){const[documents,compliance]=await Promise.all([db.collection('documents').where('status','==','Submitted').limit(50).get(),db.collection('compliance_actions').where('status','==','Pending').limit(50).get()]);result.documents=rows(documents);result.compliance=rows(compliance)}return Response.json(result)}catch(error){return jsonError(error)}}

export async function POST(request:Request){try{rateLimit(request,'operations-queue',30);const input=await request.json(),action=String(input.action||'');if(action==='support-note'){const{user,admin}=await requireStaff(request,'cases:communicate'),ref=admin.db.collection('supportCases').doc(String(input.caseId||'')),record=await ref.get(),note=String(input.note||'').trim().slice(0,2000);if(!record.exists||!note)return Response.json({ok:false,error:'Case and note are required.'},{status:400});await ref.collection('notes').add({body:note,authorId:user.id,authorEmail:user.email,createdAt:new Date()});await ref.update({lastActivityAt:new Date(),updatedAt:new Date()});return Response.json({ok:true})}if(action==='resolve-dispute'){const{user,admin}=await requireStaff(request,'disputes:decide'),contractRef=admin.db.collection('contracts').doc(String(input.contractId||'')),contract=await contractRef.get(),data=contract.data(),decision=String(input.decision||''),reason=String(input.reason||'').trim().slice(0,2000);if(!contract.exists||data?.status!=='disputed'||!['buyer','seller','cancel'].includes(decision)||!reason)return Response.json({ok:false,error:'A valid disputed contract, decision, and reason are required.'},{status:409});const updates:any={disputeStatus:'resolved',disputeDecision:decision,disputeDecisionReason:reason,disputeDecidedBy:user.id,disputeDecidedAt:new Date(),updatedAt:new Date()};if(decision==='buyer'){updates.refundStatus='requested';updates.status='disputed'}else if(decision==='seller')updates.status=data.paymentStatus==='paid'?'paid':'accepted';else updates.status='cancelled';const cases=await admin.db.collection('supportCases').where('contractId','==',contract.id).limit(1).get();await admin.db.runTransaction(async transaction=>{transaction.update(contractRef,updates);if(!cases.empty)transaction.update(cases.docs[0].ref,{status:'resolved',resolution:decision,resolvedBy:user.id,resolvedAt:new Date(),updatedAt:new Date()});transaction.set(admin.db.collection('activityLogs').doc(),{actorId:user.id,type:'dispute_decision',label:`Dispute resolved for ${decision}`,detail:contract.id,role:'dispute_officer',createdAt:new Date()})});return Response.json({ok:true,decision})}return Response.json({ok:false,error:'Unsupported queue action.'},{status:400})}catch(error){return jsonError(error)}}
